const TeamScraper = require('./teams')
const BathConfig = require('./teams/bath')
const BristolBearsConfig = require('./teams/bristol-bears')
const ExeterChiefsConfig = require('./teams/exeter-chiefs')
const GloucesterConfig = require('./teams/gloucester')
const LeicesterTigersConfig = require('./teams/leicester-tigers')
const LondonIrishConfig = require('./teams/london-irish')
const NorthamptonSaintsConfig = require('./teams/northampton-saints')
const SaleSharksConfig = require('./teams/sale-sharks')
const WaspsConfig = require('./teams/wasps')
const WorcesterWarriorsConfig = require('./teams/worcester-warriors')

new TeamScraper(BathConfig).scrapeTeamPage()
new TeamScraper(BristolBearsConfig).scrapeTeamPage()
new TeamScraper(ExeterChiefsConfig).scrapeTeamPage()
new TeamScraper(GloucesterConfig).scrapeTeamPage()
new TeamScraper(LeicesterTigersConfig).scrapeTeamPage()
new TeamScraper(LondonIrishConfig).scrapeTeamPage()
new TeamScraper(NorthamptonSaintsConfig).scrapeTeamPage()
new TeamScraper(SaleSharksConfig).scrapeTeamPage()
new TeamScraper(WaspsConfig).scrapeTeamPage()
new TeamScraper(WorcesterWarriorsConfig).scrapeTeamPage()
